name: doc_booking_app
description: "doctor's booking application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# ios
version: 1.0.2+2

# android
#version: 1.0.1+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  logger: ^2.5.0
  #  curved_navigation_bar:
  #  country_picker: ^2.0.27
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  dotted_border:
  intl:
  pinput: ^5.0.0
  dio:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  flutter_typeahead: ^5.2.0
  #  table_calendar: ^3.1.3
  google_maps_flutter: ^2.10.0
  location: ^6.0.2
  flutter_stripe: ^11.3.0
  socket_io_client: ^3.0.2
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_html: ^3.0.0-beta.2
  card_stack_widget: ^0.1.6
#  very_good_analysis: ^7.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/svgs/
